### ISSUE TITLE
The extension works fine in Desktop but not on the server.  I can see the tabs but the tab object does not display.  If I click export it actually exports data from the object.

### ISSUE THREAD

**Issue by ccherms** [dfarache/Tabbed-Container-Extension#23]

**Comment by dfarache** [comment]
which version of Qlik Sense Sever are you using?

Also, do you have the latest version of the TabbedContainer installed in your server?

**Comment by ccherms** [comment]
Qlik Sense 3.0 SR2

**Comment by dfarache** [comment]
could you please check if the latest version fixes your problem?

**Comment by ccherms** [comment]
Unfortunately it will take some time to get IT to update our Enterprise environment.
Are there know issues with 3.0 SP2 and your extension?

**Comment by dfarache** [comment]
I meant the latest version of the extension. I pushed a small change yesterday that I hope will fix your problem

**Comment by ccherms** [comment]
We reinstalled latest version but still not working.   It looks like I get a brief message in the tab window when I first open the sheet but it disappears immediately so I can’t see what it says.

**Comment by dfarache** [comment]
Which browser are you using?

Does the browser console display any errors?

**Comment by ccherms** [comment]
Tried on IE11 and Chrome.  A few lines of text flash for a brief second in the tab object but I could not see what it says.

**Comment by dfarache** [comment]
And do you see any errors in the Developer Tools Console? (to open it press F12 in Google Chrome)

**Comment by changeling76** [comment]
I confirm the same bug, QS Server 3.1. No messages in console. It worked with previous extension version (but unstable - sometimes the chart got lost until reload).

But it works with QS Desktop...

**Comment by dfarache** [comment]
Thanks for the feedback. Unfortunately, I have not been able to reproduce this issue either on Sense 3.1 SR4 -which is the one we are using- nor on the latest releases.

**Comment by dfarache** [comment]
I have just pushed a couple of changes that fix some issues that the extension had. Could you please check whether this has solved your issues?

**Comment by dfarache** [comment]
@changeling76  @ccherms could you update the extension to the latest version and check if you still see this behavior?

**Comment by mayotado** [comment]
The extension works fine in Desktop but not on the server. I can see the tabs but the tab object does not display.
The version of my Qlik Sense Server is 10.3.5
