### ISSUE TITLE
Pivot Table Export Issue

### ISSUE THREAD

**Issue by ashishxs** [dfarache/Tabbed-Container-Extension#49]
For data with commas(,), the csv export separates the data into different columns.
For example: $450,000 would be exported to csv with $450 in one column and 000 in the next column of a exported row.
That is,
Col1   Col2
A        $450,000
B        $475,000

gets exported to csv as:

Col1 Col2  Extra Col
A      $450    000
B       $475     000

Is there a way to fix it? Number formatting would always have commas, could the exported csv use a different delimiter like ; or tab?

@dfarache

**Comment by dfarache** [comment]
Hello @ashishxs 

That's a very good point. This should be fixed right away.

I am thinking of creating tab delimited CSVs by default but also giving the user the option to select between other types.

Can you check if #50 solves the issue in your case?

**Comment by ashishxs** [comment]
@dfarache Hi David,
Thanks for the quick turnaround. It still doesn't download correctly in either tab or semicolon separated format.
The numbers are broken incorrectly into different columns.

**Comment by dfarache** [comment]
@ashishxs sorry to hear that. I need to look further into it then. Will keep you updated

**Comment by ashishxs** [comment]
@dfarache I think the reason that happens is because even with tab delimiter, when a file is saved as csv, Excel(most often the default csv browsing tool) takes the comma and separates it. I used tsv format(but Excel doesn't open it by default) and it works, yet to experiment with saving as xls/xlsx  with tab delimiter.

**Comment by dfarache** [comment]
There is a way to tell Excel to use tabs for a given document:

1. Open a blank workbook
2. Go to Data -> From Text 
3. Select the file

A window will open, in which you can specify the delimiter.

**Comment by ashishxs** [comment]
@dfarache Yeah, I know about that. The issue is that Windows doesn't auto associate .tsv files with Excel, so a user has to right click and open in Excel(at least once) and then do those steps every time. Clutching at straws here, but user experience would not be as good with a tsv, I will try to save as xls with tab separator to see if it works.

**Comment by dfarache** [comment]
I'll close this issue for now and will make some time this week to add the possibility to export the data as a .xlsx file directly :)

**Comment by aaroncpc** [comment]
@dfarache I am also facing the same issue, the default program for opening CSV for most businesses is excel and it will not be displaying the right export. Really looking forward to having the option to export as .xlsx

**Comment by dfarache** [comment]
Closed by #50.

Relates to issue #54 to include .xlsx as a format in which the data can be exported.
